import React, { useMemo, useState } from 'react';
import { Profile, User, ContactRelationshipState, PhotoAccessRelationshipState } from '../../types';
import SafeImage from '../Common/SafeImage';
import { MessageIdeasModal } from '../Modals/MessageIdeasModal';

interface Props {
  profile: Profile; currentUser?: User; contactState?: ContactRelationshipState; photoAccessState?: PhotoAccessRelationshipState;
  conversationId?: string; isFavorited?: boolean; onBack: () => void; onSendContactRequest?: (p: Profile) => void;
  onAcceptContactRequest?: (id: string) => Promise<void>; onRejectContactRequest?: (id: string) => Promise<void>;
  onOpenConversation?: (id: string) => void; onRequestPhotoAccess?: (p: Profile) => void; onToggleFavorite?: (id: string) => void;
  onReport?: (p: Profile, reason: string, description?: string) => void; onBlock?: (p: Profile, reason?: string) => void;
  onStartMessage?: (p: Profile) => void; onAcceptContact?: (id: string) => Promise<void>; onRejectContact?: (id: string) => Promise<void>;
  hasUploadedPhoto?: boolean; onRequestPhotoUpload?: () => void;
}
const has = (v: unknown) => typeof v === 'string' ? v.trim().length > 0 : Array.isArray(v) ? v.length > 0 : v !== null && v !== undefined;
const Field: React.FC<{label:string;value:React.ReactNode}> = ({label,value}) => <div><span className="text-xs text-[#7D766C] block">{label}</span><span className="text-sm font-semibold text-[#211E1A] mt-0.5 block">{value}</span></div>;

export const ProfileDetailViewV2: React.FC<Props> = ({ profile, currentUser, contactState='NO_REQUEST', photoAccessState='NO_REQUEST', conversationId, isFavorited=false, onBack, onSendContactRequest, onAcceptContactRequest, onRejectContactRequest, onOpenConversation, onRequestPhotoAccess, onToggleFavorite, onReport, onBlock, onStartMessage, onAcceptContact, onRejectContact, hasUploadedPhoto=true, onRequestPhotoUpload }) => {
  const [activePhotoIndex,setActivePhotoIndex]=useState(0); const [ideasOpen,setIdeasOpen]=useState(false); const [actionLoading,setActionLoading]=useState(false);
  const photos=useMemo(()=>[profile.photoUrl,...(profile.photos||[])].filter((p,i,a)=>typeof p==='string'&&p.trim()&&a.indexOf(p)===i),[profile.photoUrl,profile.photos]);
  const currentPhoto=photos[activePhotoIndex]||photos[0]||''; const blurred=Boolean(profile.photoPrivate&&photoAccessState!=='ALLOWED');
  const primaryAction=()=>{if(!hasUploadedPhoto){onRequestPhotoUpload?.();return;}if(contactState==='NO_REQUEST'){if(onSendContactRequest){onSendContactRequest(profile);}else{onStartMessage?.(profile);}return;}if(contactState==='ACCEPTED'){if(conversationId&&onOpenConversation){onOpenConversation(conversationId);}else{onStartMessage?.(profile);}return;}};
  const tags=useMemo(()=>[profile.personality,profile.interests,profile.hobbies].flatMap(v=>typeof v==='string'?v.split(/[,;•\n]+/).map(x=>x.trim()).filter(Boolean):[]).filter((v,i,a)=>a.indexOf(v)===i),[profile.personality,profile.interests,profile.hobbies]);
  return <div className="max-w-2xl mx-auto space-y-5 pb-16 animate-fadeIn">
    <div className="flex items-center justify-between"><button onClick={onBack} className="inline-flex items-center gap-2 text-base font-semibold text-[#211E1A]"><span className="material-symbols-outlined">arrow_back</span>Retour</button><div className="flex gap-1"><button onClick={()=>onReport?.(profile,'Comportement inapproprié')} className="p-2 text-[#7D766C]"><span className="material-symbols-outlined">flag</span></button><button onClick={()=>onBlock?.(profile)} className="p-2 text-[#7D766C]"><span className="material-symbols-outlined">block</span></button></div></div>
    <div className="bg-white rounded-3xl overflow-hidden border border-[#E8E3D7] shadow-xs"><div className="relative aspect-square sm:aspect-4/3 max-h-[500px] bg-[#FAF8F2] overflow-hidden">{currentPhoto?<SafeImage src={currentPhoto} alt={profile.name} fallbackName={profile.name} className={`w-full h-full object-cover ${blurred?'blur-2xl scale-125':''}`}/>:<div className="h-full flex items-center justify-center text-[#7D766C]"><span className="material-symbols-outlined text-6xl">person</span></div>}{blurred&&<div className="absolute inset-0 bg-black/40 flex flex-col items-center justify-center text-white text-center p-6"><span className="material-symbols-outlined text-4xl">lock</span><strong className="mt-2">Photo confidentielle</strong>{onRequestPhotoAccess&&<button onClick={()=>onRequestPhotoAccess(profile)} className="mt-4 px-4 py-2 rounded-xl bg-white text-[#0F5C4D] text-xs font-bold">{photoAccessState==='PENDING'?'Demande envoyée':"Demander l'accès"}</button>}</div>}{onToggleFavorite&&<button onClick={()=>hasUploadedPhoto?onToggleFavorite(profile.id):onRequestPhotoUpload?.()} className="absolute top-4 right-4 w-11 h-11 rounded-full bg-white/95 flex items-center justify-center shadow-md"><span className="material-symbols-outlined text-2xl" style={{fontVariationSettings:isFavorited?"'FILL' 1":"'FILL' 0"}}>star</span></button>}</div>{photos.length>1&&<div className="px-5 py-3 border-t border-[#E8E3D7] flex justify-center gap-2">{photos.map((_,i)=><button key={i} onClick={()=>setActivePhotoIndex(i)} className={`h-2.5 rounded-full ${activePhotoIndex===i?'w-5 bg-[#0F5C4D]':'w-2.5 bg-[#D1CABE]'}`} />)}</div>}</div>
    <section className="bg-white rounded-3xl p-5 sm:p-7 border border-[#E8E3D7] shadow-xs space-y-4"><h1 className="font-serif-display text-3xl font-bold">{profile.name}{has(profile.age)&&<span className="font-normal text-[#7D766C] text-2xl ml-2">{profile.age} ans</span>}</h1>{profile.matchPercentage>0&&<span className="inline-flex px-3.5 py-1.5 rounded-full bg-[#EAF5F2] text-[#0F5C4D] text-xs font-semibold">{profile.matchPercentage}% compatible</span>}<div className="flex flex-wrap gap-2 text-sm text-[#575147]">{has(profile.city)&&<span>📍 {profile.city}{has(profile.country)?`, ${profile.country}`:''}</span>}{has(profile.profession)&&<span>• {profile.profession}</span>}</div><div className="flex flex-wrap gap-2">{[profile.maritalStatus,profile.education,profile.height?`${profile.height} cm`:undefined,profile.weight?`${profile.weight} kg`:undefined].filter(has).map((v,i)=><span key={i} className="px-3 py-1.5 rounded-full bg-[#EAF5F2] text-[#0F5C4D] text-xs">{String(v)}</span>)}</div></section>
    {(has(profile.ethnicity)||has(profile.originCity))&&<section className="bg-white rounded-3xl p-5 sm:p-6 border border-[#E8E3D7] shadow-xs space-y-4"><h2 className="font-serif-display text-lg font-bold">Origine</h2><div className="grid grid-cols-2 gap-4">{has(profile.ethnicity)&&<Field label="Ethnie / communauté" value={profile.ethnicity}/>} {has(profile.originCity)&&<Field label="Ville ou région d’origine" value={profile.originCity}/>}</div></section>}
    {(has(profile.religion)||has(profile.religiousPracticeDetails)||has(profile.hijabStatus)||has(profile.beardStatus))&&<section className="bg-white rounded-3xl p-5 sm:p-6 border border-[#E8E3D7] shadow-xs space-y-4"><h2 className="font-serif-display text-lg font-bold">Pratique religieuse</h2><div className="grid grid-cols-2 gap-4">{has(profile.religion)&&<Field label="Religion / courant" value={profile.religion}/>} {has(profile.religiousPracticeDetails)&&<Field label="Pratique des prières" value={profile.religiousPracticeDetails}/>} {has(profile.hijabStatus)&&<Field label={profile.gender==='female'?'Hijab / tenue':'Tenue / barbe'} value={profile.hijabStatus}/>} {profile.gender==='male'&&has(profile.beardStatus)&&<Field label="Barbe" value={profile.beardStatus}/>}</div></section>}
    {has(profile.bio)&&<section className="bg-white rounded-3xl p-5 sm:p-6 border border-[#E8E3D7] shadow-xs"><h2 className="font-serif-display text-lg font-bold mb-3">À propos</h2><p className="text-sm leading-relaxed text-[#575147] whitespace-pre-wrap">{profile.bio}</p></section>}
    {(has(profile.personality)||has(profile.familyImportance)||tags.length>0)&&<section className="bg-white rounded-3xl p-5 sm:p-6 border border-[#E8E3D7] shadow-xs space-y-4"><h2 className="font-serif-display text-lg font-bold">Personnalité & famille</h2>{has(profile.personality)&&<Field label="Trait de caractère" value={profile.personality}/>} {has(profile.familyImportance)&&<Field label="Place de la famille" value={profile.familyImportance}/>} {tags.length>0&&<div className="flex flex-wrap gap-2">{tags.map(t=><span key={t} className="px-3 py-1.5 rounded-full bg-[#EAF5F2] text-[#0F5C4D] text-xs">{t}</span>)}</div>}</section>}
    {Array.isArray(profile.values)&&profile.values.length>0&&<section className="bg-white rounded-3xl p-5 sm:p-6 border border-[#E8E3D7] shadow-xs"><h2 className="font-serif-display text-lg font-bold mb-3">Valeurs</h2><div className="flex flex-wrap gap-2">{profile.values.map(v=><span key={v} className="px-3 py-1.5 rounded-full bg-[#EAF5F2] text-[#0F5C4D] text-xs">{v}</span>)}</div></section>}
    {(has(profile.partnerCriteria)||has(profile.preferredAgeRange)||has(profile.marriageHorizon)||has(profile.polygamyOpinion))&&<section className="bg-white rounded-3xl p-5 sm:p-6 border border-[#E8E3D7] shadow-xs space-y-4"><h2 className="font-serif-display text-lg font-bold">Projet matrimonial</h2>{has(profile.partnerCriteria)&&<Field label="Ce que cette personne recherche" value={profile.partnerCriteria}/>} {has(profile.preferredAgeRange)&&<Field label="Tranche d’âge privilégiée" value={profile.preferredAgeRange}/>} {has(profile.polygamyOpinion)&&<Field label="Position sur la polygamie" value={profile.polygamyOpinion}/>} {has(profile.marriageHorizon)&&<Field label="Horizon du mariage" value={profile.marriageHorizon}/>}</section>}
    {Array.isArray(profile.dealBreakers)&&profile.dealBreakers.length>0&&<section className="bg-white rounded-3xl p-5 sm:p-6 border border-[#E8E3D7] shadow-xs"><h2 className="font-serif-display text-lg font-bold text-red-800 mb-3">Ce que cette personne n’accepte pas</h2><p className="text-sm leading-relaxed text-[#575147]">{profile.dealBreakers.join(', ')}</p></section>}
    <section className="bg-white rounded-3xl p-5 sm:p-6 border border-[#E8E3D7] shadow-xs space-y-3">{contactState==='PENDING_SENT'&&<div className="p-3 rounded-2xl bg-[#C9A45C]/15 text-[#735619] text-sm font-bold text-center">Demande de contact envoyée (en attente)</div>}{contactState==='PENDING_RECEIVED'&&<div className="flex gap-3"><button disabled={actionLoading} onClick={async()=>{setActionLoading(true);if(conversationId)await onAcceptContactRequest?.(conversationId);else await onAcceptContact?.(profile.id);setActionLoading(false)}} className="flex-1 py-3 rounded-2xl bg-[#0F5C4D] text-white text-sm font-bold">Accepter</button><button disabled={actionLoading} onClick={async()=>{setActionLoading(true);if(conversationId)await onRejectContactRequest?.(conversationId);else await onRejectContact?.(profile.id);setActionLoading(false)}} className="px-6 py-3 rounded-2xl border border-red-300 text-red-700 text-sm font-bold">Refuser</button></div>}{contactState==='ACCEPTED'&&<button onClick={primaryAction} className="w-full py-3.5 rounded-2xl bg-[#0F5C4D] text-white text-sm font-bold">Ouvrir la conversation</button>}{contactState==='NO_REQUEST'&&<button onClick={primaryAction} className="w-full py-3.5 rounded-2xl bg-[#0F5C4D] text-white text-sm font-bold">Envoyer une demande de contact</button>}{contactState==='REJECTED'&&<div className="p-3 rounded-2xl bg-stone-100 text-stone-600 text-xs font-bold text-center">Demande de contact refusée</div>}<button onClick={()=>setIdeasOpen(true)} className="w-full py-3 rounded-2xl border border-[#E8E3D7] text-sm font-bold">💡 Idées de message</button><p className="text-center text-xs text-[#7D766C]">Demandes aujourd’hui {currentUser?.dailyContactsCount??0}/3</p></section>
    <MessageIdeasModal isOpen={ideasOpen} onClose={()=>setIdeasOpen(false)} profile={profile} onSelectIdea={()=>{setIdeasOpen(false);primaryAction()}}/>
  </div>;
};
